services:

    page:
        class: Sim\AppBundle\Paginator\Paginator
        arguments: [@knp_paginator , @service_container]

    twig.extension.translate:
        class: Sim\AppBundle\Twig\TranslationExtension
        arguments: [@service_container]
        tags:
           - { name: twig.extension }

    event:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Sim\AppBundle\Entity\Event ]

    connect:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Sim\AppBundle\Entity\Connect ]

    client:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Sim\AppBundle\Entity\Client ]

    project:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Sim\AppBundle\Entity\Project ]

    log:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Gedmo\Loggable\Entity\LogEntry ]

    fluent:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Sim\AppBundle\Entity\Fluent ]